# Generated by Django 5.1.6 on 2025-03-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="reg_key",
            new_name="reg_key_id",
        ),
    ]
