# Generated by Django 5.1.6 on 2025-03-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_regkey_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regkey",
            name="used",
            field=models.BooleanField(default=True),
        ),
    ]
