# Generated by Django 5.1.6 on 2025-03-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_regkey_used"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="reg_key_id",
            new_name="reg_key",
        ),
    ]
