# Generated by Django 5.1.6 on 2025-04-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(db_index=True, default='01/01/2025'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user_tag', 'date'], name='tasks_task_user_ta_596f71_idx'),
        ),
    ]
